# Site


name: "Zouhair M"
title: "Zouhair M"
description: Different musings and projects by Zouhair

logo: 'assets/img/avatar.png'
favicon: 'assets/images/favicon.ico'
# baseurl: /
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  zouhair:
    name: Zouhair Mahboubi
    display_name: Zouhair
    gravatar: 3cada6cba63f6de920dfacde7085675e
    email: zouhair.mahboubi _at_ gmail
    web: https://zouhairm.github.io
    linkedin: https://linkedin.com/in/zouhairm
    github: https://github.com/zoohair
    description: "Business and Technical Leader, Ph.D."
    calendar: ./calendar.html
    social:
      - title: linkedin
        url: https://linkedin.com/in/zouhairm
      - title: file-pdf
        url: ./ZouhairM_resume.pdf
      - title: github
        url: https://github.com/zoohair
      - title: facebook
        url: https://facebook.com/zoohair
      - title: envelope
        url: mailto:zouhair.mahboubi@gmail

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot.
# Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
imageFolder: 'assets/img/'



exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]